var username = {
login: "bhare1987",
id: 9021049,
avatar_url: "https://avatars.githubusercontent.com/u/9021049?v=3",
gravatar_id: "",
url: "https://api.github.com/users/bhare1987",
html_url: "https://github.com/bhare1987",
followers_url: "https://api.github.com/users/bhare1987/followers",
following_url: "https://api.github.com/users/bhare1987/following{/other_user}",
gists_url: "https://api.github.com/users/bhare1987/gists{/gist_id}",
starred_url: "https://api.github.com/users/bhare1987/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/bhare1987/subscriptions",
organizations_url: "https://api.github.com/users/bhare1987/orgs",
repos_url: "https://api.github.com/users/bhare1987/repos",
events_url: "https://api.github.com/users/bhare1987/events{/privacy}",
received_events_url: "https://api.github.com/users/bhare1987/received_events",
type: "User",
site_admin: false,
name: "Brandon Hare",
company: "Blackbaud",
blog: null,
location: "Charleston, SC",
email: null,
hireable: null,
bio: null,
public_repos: 10,
public_gists: 0,
followers: 2,
following: 9,
created_at: "2014-10-04T20:05:09Z",
updated_at: "2016-02-05T01:29:04Z"
}
